### ISSUE TITLE
discord.js/src/errors does not exist?

### ISSUE THREAD

**Issue by mrpotatofactory** [devsnek/discord-rpc#4]
https://github.com/devsnek/discord-rpc/blob/afb30e530ff5e1dd8ce931c840d515de087b7914/src/index.js#L1

I don't think this is a valid library.

**Comment by devsnek** [comment]
it actually does work (see https://github.com/nodejs/node/blob/44d3e17985befbd45457d5ad7f0a0387849e1b2f/lib/module.js#L512)
