### ISSUE TITLE
Problem setting this up with Electron

### ISSUE THREAD

**Issue by armaldio** [devsnek/discord-rpc#5]
I'm trying to add rich presence to an electron app.

I've tried the default code:
After accepting discord auth, it redirects to my redirect Url, but not access token, I got this instead : `http://localhost:4242/oauth/redirect#error=invalid_scope`
So I tried removing scopes. I just kept `rpc.api` scope.
This time, I get the token.

But when I try to 
```js
client.login(config.clientId, {
        accessToken: token,
        scopes     : config.scopes
});
```
all I get is 

![https://i.imgur.com/sgqLe8I.png](https://i.imgur.com/sgqLe8I.png)

Could you help on that ?
Thanks

**Comment by devsnek** [comment]
you can't use `rpc.api` without being whitelisted. if you want to use rich presence you should use IPC not WebSockets, see the source code in this repo for a pretty good implementation.

**Comment by devsnek** [comment]
you can't use WebSocket for rich presence, you have to use IPC.

**Comment by armaldio** [comment]
If I use the Rich Presence example on the readme I get: 
`Cannot read property 'accessToken' of undefined`

**Comment by armaldio** [comment]
Ok, updated from beta1 to beta2 and now it show `Ready, setting rich presence` but no rich presence
It still show the old format

**Comment by devsnek** [comment]
https://discordapp.com/developers/docs/rich-presence/faq#q-i-don't-see-any-playing-status-for-my-game

**Comment by armaldio** [comment]
I've already done that.
As i've told you `It still show the old format`

I can also see that the event SET_ACTIVITY  is correctly sent to discord with - from what I can understand - correct datas

**Comment by armaldio** [comment]
Is there an error event I can listen to ?

**Comment by armaldio** [comment]
I got it working now.
It's working with nodejs and electron

For anyone in the same case as me, you must put the code inside the main.js file and not the renderer.js file.
I still don't know why, I will try to find more infos.
You can still communicate between the main and the renderer process using IPC or any other methods

**Comment by devsnek** [comment]
it has to go in main because its a separate process from renderer. Discord will think that your process has no window and therefore won't think its a game if its in the renderer

**Comment by armaldio** [comment]
Ok, thanks 👍
