### ISSUE TITLE
Unknown Error when trying to connect to a bot without a user (Example)

### ISSUE THREAD

**Issue by y21** [devsnek/discord-rpc#6]
Electron works fine and the window appears, but the console is literally flooded by errors. 
Edit: And the Rich Presence doesn't appear on the bot neither on the bot owner's account.
![image](https://user-images.githubusercontent.com/30553356/32979457-e07cdc60-cc55-11e7-8d7f-bd87ae0e5e3d.png)
I noticed that all ~15 Seconds a new UnhandledPromiseRejectionWarning appears in the console.

>   setInterval(() => {
    setActivity();
  }, 15e3);
});
>

That could be the error, since `setActivity()` is getting called every 15 Seconds.
Node: v8.9.1
NPM: v5.5.1
Discord-RPC: 3.0.0-beta.2
PS: I didn't change anything in the <RPC>.setActivity() Function.

**Comment by TrueBoxGuy** [comment]
Could you try using `process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
});`
in your code

**Comment by y21** [comment]
That doesn't log the errors and the RichPresence still doesn't appear.
![image](https://user-images.githubusercontent.com/30553356/32980083-a01de4f6-cc60-11e7-96c5-c994ab2e0c68.png)

**Comment by TrueBoxGuy** [comment]
Oops, I think my code was bad or for another lang. Try my updated code, I edited the msg

**Comment by y21** [comment]
As i said, no unhandledRejections anymore. Any ideas why the RichPresence doesn't show?

**Comment by TrueBoxGuy** [comment]
The reason for that was because the code stops it from logging. Try updating it with the new code

**Comment by y21** [comment]
I tried that with both codes and once without. Anyways, that's not the problem. 
> Any ideas why the RichPresence doesn't show?

**Comment by DriftTech** [comment]
@y21 Please add the electron as a game in Discord
![image](https://user-images.githubusercontent.com/19936045/32980856-b8d4325c-cc33-11e7-9b54-158b494ad4cb.png)

**Comment by y21** [comment]
@DriftTech Thank you very much.  That works.
