### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by MrJacz** [devsnek/discord-rpc#7]
Getting this error while trying the example i will confirm that
1st) Discord client is on
2nd) discord detects the game
```js
{ Error: connect ENOENT \\?\pipe\discord-ipc-0
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\?\\pipe\\discord-ipc-0' }```

**Comment by MrJacz** [comment]
Update: works on canary

**Comment by devsnek** [comment]
probs a discord issue then but I'll leave this open just in case

**Comment by MrJacz** [comment]
I'm guessing RPC is not connecting on discord's side i'll debug more later

**Comment by MrJacz** [comment]
ENOENT meaning discord client isnt there basically 🤔
