### ISSUE TITLE
Allow changing status type

### ISSUE THREAD

**Issue by justdotJS** [devsnek/discord-rpc#9]
Allow changing status type (`playing`, `watching`, `listening`) for Rich Presence.

Note an example of a `listening` Rich Presence on the developers testing the Spotify integration's Rich Presences.

Also, https://github.com/hydrabolt/discord.js/issues/2103 is a (closed) discord.js issue with an example of a rich presence type:
```javascript
client.user.setPresence({
    activity: {
//[...]
        name: "",
        type: "LISTENING",
        details: "",
        state: ""
//[...]
    }
});```

**Comment by FOG-Yamato** [comment]
The internal RPC server methods do not accept the presence type as a argument, the only way for you to change it is to connect to the API and do it from there

**Comment by justdotJS** [comment]
That sucks... can someone at least try? Would be sad not to have types on local RPC :/

**Comment by FOG-Yamato** [comment]
Did you understand what I said? the RPC connection does not accept the type, it's something that Discord handles, we can't change it.
